
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasCliente;


/**
 *
 * @author ADMIN
 */
public class InterfazCliente extends javax.swing.JFrame {

    /**
     * Creates new form InterfazCliente
     */
    public InterfazCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnSolitarServicio = new javax.swing.JButton();
        BtnCancelarServicio = new javax.swing.JButton();
        BtnConsultarServicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnSolitarServicio.setBackground(new java.awt.Color(0, 0, 0));
        BtnSolitarServicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnSolitarServicio.setForeground(new java.awt.Color(255, 255, 255));
        BtnSolitarServicio.setText("Solicitar servicio");
        BtnSolitarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSolitarServicioActionPerformed(evt);
            }
        });

        BtnCancelarServicio.setBackground(new java.awt.Color(0, 0, 0));
        BtnCancelarServicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnCancelarServicio.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelarServicio.setText("Cancelar servicio");
        BtnCancelarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarServicioActionPerformed(evt);
            }
        });

        BtnConsultarServicio.setBackground(new java.awt.Color(0, 0, 0));
        BtnConsultarServicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnConsultarServicio.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsultarServicio.setText("Consultar servicio");
        BtnConsultarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultarServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnConsultarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnSolitarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCancelarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(BtnSolitarServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCancelarServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnConsultarServicio)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSolitarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSolitarServicioActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SolicitarServicio ss = new SolicitarServicio();
        ss.setVisible(true);
        
        
    }//GEN-LAST:event_BtnSolitarServicioActionPerformed

    private void BtnCancelarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarServicioActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        CancelarServicio ss = new CancelarServicio();
        ss.setVisible(true);
        
    }//GEN-LAST:event_BtnCancelarServicioActionPerformed

    private void BtnConsultarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultarServicioActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ConsultarServicio ss = new ConsultarServicio();
        ss.setVisible(true);
        
    }//GEN-LAST:event_BtnConsultarServicioActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelarServicio;
    private javax.swing.JButton BtnConsultarServicio;
    private javax.swing.JButton BtnSolitarServicio;
    // End of variables declaration//GEN-END:variables
}
