/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasGeneral;

import com.sun.awt.AWTUtilities;
import DBConnection.CaException;

import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.Cliente;
import DAOs.Mensajeria;
import logica.Persona;
import logica.Telefono;


/**
 *
 * @author Julian
 */
public class RegistroCliente extends javax.swing.JDialog {

    InicioSesion is;

    /**
     * Creates new form Registrae
     */
    public RegistroCliente(java.awt.Frame parent, String title) {
        super(parent, title);
        initComponents();
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        AWTUtilities.setWindowShape(this, forma);
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator5 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        TextFieldPrimNom = new javax.swing.JTextField();
        PrimerNombre = new javax.swing.JLabel();
        SegundoNombre = new javax.swing.JLabel();
        TextFieldSegNom = new javax.swing.JTextField();
        TipoDeId = new javax.swing.JLabel();
        jComboBoxTipoId = new javax.swing.JComboBox<>();
        NumeroDeId = new javax.swing.JLabel();
        TextFieldNumId = new javax.swing.JTextField();
        Correo = new javax.swing.JLabel();
        TextFieldCorreo = new javax.swing.JTextField();
        Direccion = new javax.swing.JLabel();
        TextFieldDireccion = new javax.swing.JTextField();
        ButtonRegresar = new javax.swing.JButton();
        PrimerApellido = new javax.swing.JLabel();
        SegundoApellido = new javax.swing.JLabel();
        TextFieldPrimApe = new javax.swing.JTextField();
        TextFieldSegApe = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        ButtonRegistrarme1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        Direccion1 = new javax.swing.JLabel();
        TextFieldTelefono = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();

        jSeparator5.setBackground(new java.awt.Color(3, 152, 158));
        jSeparator5.setForeground(new java.awt.Color(3, 152, 158));
        jSeparator5.setAlignmentX(0.8F);

        jSeparator8.setBackground(new java.awt.Color(3, 152, 158));
        jSeparator8.setForeground(new java.awt.Color(3, 152, 158));
        jSeparator8.setAlignmentX(0.8F);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextFieldPrimNom.setBackground(new java.awt.Color(44, 62, 80));
        TextFieldPrimNom.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        TextFieldPrimNom.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldPrimNom.setBorder(null);
        jPanel1.add(TextFieldPrimNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 200, 30));

        PrimerNombre.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        PrimerNombre.setForeground(new java.awt.Color(255, 255, 255));
        PrimerNombre.setText("Primer Nombre");
        jPanel1.add(PrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 150, 20));

        SegundoNombre.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        SegundoNombre.setForeground(new java.awt.Color(255, 255, 255));
        SegundoNombre.setText("Segundo Nombre");
        jPanel1.add(SegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 120, 150, -1));

        TextFieldSegNom.setBackground(new java.awt.Color(44, 62, 80));
        TextFieldSegNom.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        TextFieldSegNom.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldSegNom.setBorder(null);
        jPanel1.add(TextFieldSegNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 121, 193, -1));

        TipoDeId.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        TipoDeId.setForeground(new java.awt.Color(255, 255, 255));
        TipoDeId.setText("Tipo de Documento");
        jPanel1.add(TipoDeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 170, -1));

        jComboBoxTipoId.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBoxTipoId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "TI" }));
        jComboBoxTipoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoIdActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxTipoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 72, -1));

        NumeroDeId.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        NumeroDeId.setForeground(new java.awt.Color(255, 255, 255));
        NumeroDeId.setText("N° de documento");
        jPanel1.add(NumeroDeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 170, -1));

        TextFieldNumId.setBackground(new java.awt.Color(44, 62, 80));
        TextFieldNumId.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        TextFieldNumId.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldNumId.setBorder(null);
        jPanel1.add(TextFieldNumId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 200, 20));

        Correo.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        Correo.setForeground(new java.awt.Color(255, 255, 255));
        Correo.setText("Correo");
        jPanel1.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 80, -1));

        TextFieldCorreo.setBackground(new java.awt.Color(44, 62, 80));
        TextFieldCorreo.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        TextFieldCorreo.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldCorreo.setBorder(null);
        jPanel1.add(TextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 200, 20));

        Direccion.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        Direccion.setForeground(new java.awt.Color(255, 255, 255));
        Direccion.setText("Teléfono");
        jPanel1.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 110, -1));

        TextFieldDireccion.setBackground(new java.awt.Color(44, 62, 80));
        TextFieldDireccion.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        TextFieldDireccion.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldDireccion.setBorder(null);
        TextFieldDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(TextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 200, -1));

        ButtonRegresar.setBackground(new java.awt.Color(0, 0, 0));
        ButtonRegresar.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRegresar.setText("Regresar");
        ButtonRegresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ButtonRegresar.setBorderPainted(false);
        ButtonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonRegresar.setOpaque(false);
        ButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 110, 30));

        PrimerApellido.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        PrimerApellido.setForeground(new java.awt.Color(255, 255, 255));
        PrimerApellido.setText("Primer Apellido");
        jPanel1.add(PrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 162, 170, -1));

        SegundoApellido.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        SegundoApellido.setForeground(new java.awt.Color(255, 255, 255));
        SegundoApellido.setText("Segundo Apellido");
        jPanel1.add(SegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 180, -1));

        TextFieldPrimApe.setBackground(new java.awt.Color(44, 62, 80));
        TextFieldPrimApe.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        TextFieldPrimApe.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldPrimApe.setBorder(null);
        jPanel1.add(TextFieldPrimApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 160, 193, 20));

        TextFieldSegApe.setBackground(new java.awt.Color(44, 62, 80));
        TextFieldSegApe.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        TextFieldSegApe.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldSegApe.setBorder(null);
        jPanel1.add(TextFieldSegApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 200, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Titulo formulario.PNG"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MUF.PNG"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        jSeparator2.setBackground(new java.awt.Color(3, 152, 158));
        jSeparator2.setForeground(new java.awt.Color(3, 152, 158));
        jSeparator2.setAlignmentX(0.8F);
        jSeparator2.setOpaque(true);
        jSeparator2.setPreferredSize(new java.awt.Dimension(0, 3));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 200, 3));

        jSeparator3.setBackground(new java.awt.Color(3, 152, 158));
        jSeparator3.setForeground(new java.awt.Color(3, 152, 158));
        jSeparator3.setAlignmentX(0.8F);
        jSeparator3.setOpaque(true);
        jSeparator3.setPreferredSize(new java.awt.Dimension(0, 3));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 200, 3));

        jSeparator4.setBackground(new java.awt.Color(3, 152, 158));
        jSeparator4.setForeground(new java.awt.Color(3, 152, 158));
        jSeparator4.setAlignmentX(0.8F);
        jSeparator4.setOpaque(true);
        jSeparator4.setPreferredSize(new java.awt.Dimension(0, 3));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 200, -1));

        jSeparator6.setBackground(new java.awt.Color(3, 152, 158));
        jSeparator6.setForeground(new java.awt.Color(3, 152, 158));
        jSeparator6.setAlignmentX(0.8F);
        jSeparator6.setOpaque(true);
        jSeparator6.setPreferredSize(new java.awt.Dimension(0, 3));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 200, -1));

        jSeparator7.setBackground(new java.awt.Color(3, 152, 158));
        jSeparator7.setForeground(new java.awt.Color(3, 152, 158));
        jSeparator7.setAlignmentX(0.8F);
        jSeparator7.setOpaque(true);
        jSeparator7.setPreferredSize(new java.awt.Dimension(0, 3));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 200, 3));

        jSeparator10.setBackground(new java.awt.Color(3, 152, 158));
        jSeparator10.setForeground(new java.awt.Color(3, 152, 158));
        jSeparator10.setAlignmentX(0.8F);
        jSeparator10.setOpaque(true);
        jSeparator10.setPreferredSize(new java.awt.Dimension(0, 3));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 200, -1));

        ButtonRegistrarme1.setBackground(new java.awt.Color(0, 0, 0));
        ButtonRegistrarme1.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ButtonRegistrarme1.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRegistrarme1.setText("Registrarme");
        ButtonRegistrarme1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ButtonRegistrarme1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonRegistrarme1.setOpaque(false);
        ButtonRegistrarme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegistrarme1ActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonRegistrarme1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 110, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jSeparator11.setBackground(new java.awt.Color(3, 152, 158));
        jSeparator11.setForeground(new java.awt.Color(3, 152, 158));
        jSeparator11.setAlignmentX(0.8F);
        jSeparator11.setOpaque(true);
        jSeparator11.setPreferredSize(new java.awt.Dimension(0, 3));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 200, -1));

        Direccion1.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        Direccion1.setForeground(new java.awt.Color(255, 255, 255));
        Direccion1.setText("Dirección");
        jPanel1.add(Direccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 110, -1));

        TextFieldTelefono.setBackground(new java.awt.Color(44, 62, 80));
        TextFieldTelefono.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        TextFieldTelefono.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldTelefono.setBorder(null);
        TextFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(TextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 200, -1));

        jSeparator12.setBackground(new java.awt.Color(3, 152, 158));
        jSeparator12.setForeground(new java.awt.Color(3, 152, 158));
        jSeparator12.setAlignmentX(0.8F);
        jSeparator12.setOpaque(true);
        jSeparator12.setPreferredSize(new java.awt.Dimension(0, 3));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTipoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoIdActionPerformed

    }//GEN-LAST:event_jComboBoxTipoIdActionPerformed

    private void TextFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDireccionActionPerformed

    private void ButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegresarActionPerformed
        InicioSesion inicio = new InicioSesion();
        this.setVisible(false);
        inicio.setLocationRelativeTo(null);
        inicio.setVisible(true);
        

        

    }//GEN-LAST:event_ButtonRegresarActionPerformed

    private void ButtonRegistrarme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegistrarme1ActionPerformed
        if (!TextFieldPrimNom.getText().isEmpty() && !TextFieldPrimApe.getText().isEmpty()
                && !TextFieldNumId.getText().isEmpty() && !TextFieldCorreo.getText().isEmpty()) {

            try {
                Mensajeria mens = new Mensajeria();
                Persona person = mens.getPersona();
                Cliente client = mens.getCliente();
                Telefono telefono = mens.getTelefono();

                String tipoId = jComboBoxTipoId.getSelectedItem().toString();
                long numeroId = Long.parseLong(TextFieldNumId.getText());
                person.setN_rol("Cliente");
                person.setN_primer_nombre(TextFieldPrimNom.getText());
                person.setN_segundo_nombre(TextFieldSegNom.getText());
                person.setN_primer_apellido(TextFieldPrimApe.getText());
                person.setN_segundo_apellido(TextFieldSegApe.getText());
                person.setO_correo(TextFieldCorreo.getText());

                person.setK_tipo_id(tipoId);
                person.setK_numero_id(numeroId);
                
                
                client.setK_tipo_id(tipoId);
                client.setK_numero_id(numeroId);
                client.setN_direccion(TextFieldDireccion.getText());
                
                telefono.setK_tipo_id(tipoId);
                telefono.setK_numero_id(numeroId);
                telefono.setTelefono(Long.parseLong(TextFieldTelefono.getText()));
                
                mens.IncluirPersona();
                mens.IncluirCliente();
                mens.IncluirTelefono();
                JOptionPane.showMessageDialog(null, "Fué Registrado con éxito");

                

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingresa un numero de identificación valido.");
            } catch (CaException ex) {
                Logger.getLogger(RegistroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Hay campos obligatorios que tienes que llenar.");
        }
    }//GEN-LAST:event_ButtonRegistrarme1ActionPerformed

    private void TextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTelefonoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRegistrarme1;
    private javax.swing.JButton ButtonRegresar;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Direccion1;
    private javax.swing.JLabel NumeroDeId;
    private javax.swing.JLabel PrimerApellido;
    private javax.swing.JLabel PrimerNombre;
    private javax.swing.JLabel SegundoApellido;
    private javax.swing.JLabel SegundoNombre;
    private javax.swing.JTextField TextFieldCorreo;
    private javax.swing.JTextField TextFieldDireccion;
    private javax.swing.JTextField TextFieldNumId;
    private javax.swing.JTextField TextFieldPrimApe;
    private javax.swing.JTextField TextFieldPrimNom;
    private javax.swing.JTextField TextFieldSegApe;
    private javax.swing.JTextField TextFieldSegNom;
    private javax.swing.JTextField TextFieldTelefono;
    private javax.swing.JLabel TipoDeId;
    private javax.swing.JComboBox<String> jComboBoxTipoId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
